### ISSUE TITLE
Update description is broken

### ISSUE THREAD

**Issue by g3939434** [dgutov/bmreplace#27]
STR:

1) Bookmark a website with description
2) Change the bookmark's name and description
3) Replace bookmark
4) Name had changed but not description

`Update the bookmark description` was checked in option page

**Comment by dgutov** [comment]
Yes, I can see that. But to be fair, the prompt at 3 only promises to update the name.

A related problem I see there is that if only the description has changed, you won't be offered to update it.

**Comment by dgutov** [comment]
https://addons.mozilla.org/en-US/firefox/addon/bmreplace/versions/

Should be fixed in 1.5.10 now.
