### ISSUE TITLE
Keyword moving to updated bookmark broken by recent Firefox update?

### ISSUE THREAD

**Issue by OwenAR** [dgutov/bmreplace#28]
I just noticed this a couple days ago after updating my Firefox to 40.0 (from 38.0, I think).

I use bookmark keywords for the comics I read a bit of every once in a while. For example, "0dc" is for a bookmark named "Dinosaur Comics".

It used to be, when I used bmreplace, the resulting updated bookmark would end up having the keyword.

That is, the bookmark named "Dinosaur Comics" would go from having old location URL 1, to having the new location URL 2, and it would still have the keyword "0dc". Then, when I entered "0dc" into the address bar, it would take me to the new URL 2.

Now what happens is:

- "Dinosaur Comics" goes from having old location URL 1 to having the new location URL 2.

- But it no longer has the keyword "0dc".

- Searching my bookmarks library, I can't find *any* bookmarks that have the keyword "0dc".

- Nevertheless, entering "0dc" into the address bar takes me to old location URL 1, as though the old, apparently replaced bookmark still existed.

**Comment by dgutov** [comment]
By "keywords" do you mean tags?

I've just tried it in 42.0a2, and it seems to transfer tags just fine.

**Comment by OwenAR** [comment]
No, I mean keywords.

If your Firefox bookmark library interface looks like mine, you'll have to hit the little `^ More` button to see the field.

Their primary use is, I think, supposed to be for stuff like looking stuff up in dictionaries.

Like, if you had a bookmark with the location url:

http://www.wordreference.com/enfr/%s

and gave it the keyword "ef", then when you enter "ef cheese" into the address bar, it'll take you to:

http://www.wordreference.com/enfr/cheese

But you can just use keywords without a `%s` portion in the "location" field of the bookmark, in which case entering the keyword into the address bar just takes you to the bookmark like I described above.

**Comment by dgutov** [comment]
I see, thanks.

It seems the keywords are stored differently now. Instead of of being associated with bookmarks, they're associated with URLs directly, like described here: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Using_the_Places_keywords_API

So, where I didn't have to do anything before, as long as the previous bookmark instance was reused, now I'd have to use the new API.

**Comment by dgutov** [comment]
Unfortunately, the few initial attempts didn't get me anywhere. I'll try again later.

**Comment by OwenAR** [comment]
Well, thanks for immediately trying to fix a feature you didn't even know existed, let alone use yourself!

I vaguely remember seeing some news article in the past couple weeks about Firefox updates. It was basically complaining that they're ruining everything, but then, one should expect to see "THEY'RE RUINING EVERYTHING!" reports in response to pretty much any change made to anything, so it's hard to tell when they're true when you're just a casual observer.

So I'm curious, does this API-ification thing they've done to the keyword feature look "short -term inconvenient but long-term makes sense"? Or *are*they just ruining everything? xD

**Comment by dgutov** [comment]
> trying to fix a feature you didn't even know existed, let alone use yourself!

Well, it sounds like a legitimate use case, and it shouldn't be too hard to support. Or so it seems.

> So I'm curious, does this API-ification thing they've done to the keyword feature look "short -term inconvenient but long-term makes sense"?

It's not really "API-fication". There was a previous API (and it's still available, though deprecated), I just didn't have to use it before.

I moderately disagree with this specific change, because it makes things harder for me. On the other hand, the new interface is simpler and uses Promises, which the Firefox team is trying to push for lately. So the answer is "yes, probably".

Same with the whole WebExtensions push: I've got no big love for XUL, but we'll have to see just how comprehensive the new API will turn out. It's a process.

**Comment by OwenAR** [comment]
Yeah, I figured it was an over-reaction. (The article I'm vaguely remembering was saying something like: "It's not immediately obvious how this early prototype of the new system could support all the features of Greasemonkey, therefore Greasemonkey is going to be permanently broken!" so yeah. Suspicious.)

But yeah, still, thanks man.

**Comment by OwenAR** [comment]
By the way, did you ever get around to fixing this? I just went back to firefox 38.5.0, because I found I was missing it quite a bit. It kinda fills the same role in the browser that aliases do in the shell.

**Comment by dgutov** [comment]
> I just went back to firefox 38.5.0, because I found I was missing it quite a bit.

Just for this extension? That's flattering.

All right, thanks for the reminder, I'll try to get it fixed this week.

**Comment by dgutov** [comment]
Hey there!

Sorry it took so long. I've uploaded the new version that should handle it now, see https://addons.mozilla.org/en-US/firefox/addon/bmreplace/versions/

**Comment by OwenAR** [comment]
Oh hey, thanks. ^^

Honestly, I can't remember the last time I noticed anything getting *better* from updating Firefox... usually it just throws away my custom hotkeys or develops some irritating new bug or something. XD

I should give that a try sometime soon though.

**Comment by dgutov** [comment]
It does get faster bit by bit, IME. And Youtube really started using HTML5 for all videos a few releases ago. I think it was after 38, on my platform (GNU/Linux).

**Comment by OwenAR** [comment]
Hm, so it should work with Firefox 44.0 and bmreplace 1.5.10?

I just updated to those on my little spare computer, and it still has the same bug behavior (as I originally described).

I also tested it by making and updating some bookmarks from a site completely new to me, to make sure I wasn't getting any weird interactions with bookmarks created in a slightly different format in old FF versions or something.

And I double-checked on my main computer (with 38.6.0 and 1.5.8) that the same process works the way I thought it should.

**Comment by dgutov** [comment]
Terribly sorry, I didn't test it properly last time. Should be fixed in 1.5.11: https://addons.mozilla.org/en-US/firefox/addon/bmreplace/versions/

**Comment by OwenAR** [comment]
(Hey, sorry it took me so long to get back to you.)

I finally got around to updating both my little spare computer and my main computer.

Firefox 44.0.2 and bmreplace 1.5.11 on both, tested and working fine!

Thanks again! ^^

**Comment by dgutov** [comment]
:sunny:
