### ISSUE TITLE
Stopped working after yesterdays Nightly build

### ISSUE THREAD

**Issue by SLK350** [dgutov/bmreplace#29]
After yesterdays Nightly update Bookmark Replace stopped working and icon is missing.

**Comment by SLK350** [comment]
I think this is the fix that's causing problems. https://bugzilla.mozilla.org/show_bug.cgi?id=1220564

**Comment by dgutov** [comment]
Thanks for the report!

I don't use Nightly; could you make sure the new version fixes the problem for you? I've uploaded the xpi at https://github.com/dgutov/bmreplace/releases/download/1.5.8/bmreplace.xpi

**Comment by SLK350** [comment]
Working now, thanks.
