### ISSUE TITLE
Broken in nightly

### ISSUE THREAD

**Issue by tomlevels** [dgutov/bmreplace#30]
In the latest nightly (today), the extension sems broken. Both the icon and the menu are gone. Any ideas why?

**Comment by dgutov** [comment]
See #29. I've uploaded the new version now. It shouldn't take too long to get reviewed.

**Comment by tomlevels** [comment]
Thanks for the quick update, it is working fine.
Sorry for the duplicate issue, I didn't the other one because of the 
default filter.

Greetings,
Tom

**Comment by dgutov** [comment]
No problem. Guess I closed the other one prematurely.
