### ISSUE TITLE
Update bookmark window, size?

### ISSUE THREAD

**Issue by SLK350** [dgutov/bmreplace#31]
This is more of a request. I find the update bookmark window way to small, can you please let user change size with a setting or code it yourself? It always reverts to it's default size after changing size.

Thanks

**Comment by dgutov** [comment]
You can change its size through the preferences (see the last two options).

**Comment by SLK350** [comment]
Thanks, I completely missed that. Is it a new option maybe?

 

Från: Dmitry Gutov [mailto:notifications@github.com] 
Skickat: den 16 januari 2016 23:39
Till: dgutov/bmreplace <bmreplace@noreply.github.com>
Kopia: SLK350 <karl-johan@vmomail.se>
Ämne: Re: [bmreplace] Update bookmark window, size? (#31)

 

You can change its size through the preferences (see the last two options).

**Comment by dgutov** [comment]
You could call it new, I suppose, compared to the extension's age. It was added in 1.5.6, last August.
