### ISSUE TITLE
Stopped working todays nightly

### ISSUE THREAD

**Issue by SLK350** [dgutov/bmreplace#32]
Stopped working today using Nightly x64 build when running with e10s. When I disable e10s in settings it starts working again.

Nothing happens when I click Bookmark replace icon.

**Comment by dgutov** [comment]
Again? :(

Did they disable CPOW now?

**Comment by dgutov** [comment]
Does the error console say something interesting?

**Comment by SLK350** [comment]
I believe they did. https://bugzilla.mozilla.org/show_bug.cgi?id=1233497

**Comment by SLK350** [comment]
These lines show up in error console:

> unsafe CPOW usage main.js:39:8
unsafe CPOW usage main.js:40:8
unsafe CPOW usage main.js:40:14
Error: unsafe CPOW usage forbidden PlacesUIUtils.jsm:582:9

**Comment by dgutov** [comment]
Thanks! For the time being, you should be able to work around this by setting `dom.ipc.cpows.forbid-unsafe-from-browser` to true.

**Comment by dgutov** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1244343

**Comment by tomlevels** [comment]
The setting dom.ipc.cpows.forbid-unsafe-from-browser is not working for me, is that correct? I am using the nightly channel.

**Comment by dgutov** [comment]
@tomlevels Could you please look into the Error Console, and see if some other errors appear when you click on this addon's button?

**Comment by tomlevels** [comment]
I will investigate further since on another PC it is working (with or without the option). Maybe it is related to the fact that the other machine uses a 64bit build of Firefox.

**Comment by dgutov** [comment]
Please see the new version I've just published: https://addons.mozilla.org/en-US/firefox/addon/bmreplace/versions/?page=1#version-1.6.0

**Comment by tomlevels** [comment]
Working great again, thanks for the update!

**Comment by tomlevels** [comment]
Thanks for the update!
