### ISSUE TITLE
New 1.6 version don't work at all.

### ISSUE THREAD

**Issue by SLK350** [dgutov/bmreplace#34]
Using latest Nightly 64bit I tried with CPOW enabled and disabled. Did set "xpinstall.signatures.required" to false to install it. Nothing happens when I click button in toolbar.

**Comment by dgutov** [comment]
Is there anything in the Error Console?

**Comment by SLK350** [comment]
No.

**Comment by dgutov** [comment]
Have you tried restarting?

**Comment by SLK350** [comment]
Yes.

**Comment by dgutov** [comment]
I've just downloaded the 64-bit 49.0a1 (2016-04-30) Nightly and tried it out a test profile.

Installing Replace Bookmark 1.6.0 from addons.mozilla.org (and restarting if there was a previous version installed, to avoid a caching problem) makes it work without a hitch, as far as I can see.

Have you tried it in a new profile? Not sure what to suggest next.

**Comment by dgutov** [comment]
> tried with CPOW enabled and disabled

BTW, you can only turn on or off the multi-process mode, as a user. Whether to use the CPOWs in the multi-process mode, is something that an addon decides and expresses in its install manifest.

**Comment by SLK350** [comment]
Just tried a fresh profile and still no luck.

**Comment by dgutov** [comment]
Which version of Nightly do you have installed? And on what OS (though that shouldn't make any difference)?

**Comment by SLK350** [comment]
I tried nightlies both Swedish and US v49a1 64bit from yesterday and today. I'm running Windows 10 Pro 64bit build 14332.

**Comment by dgutov** [comment]
OK, sorry about that. I've tried it again with a pristine profile and saw the problem (for some reasons it didn't manifest in a test profile with a couple of addons installed). Thanks for report, I'll upload the updated version now.

**Comment by dgutov** [comment]
https://addons.mozilla.org/en-US/firefox/addon/bmreplace/versions/?page=1#version-1.6.1

**Comment by dgutov** [comment]
Note: I've found the now fixed error by looking in the error console. Or, how Firefox calls it now, Browser Console.

Not to be mistaken with the Web Console which only shows errors from the web content.
