### ISSUE TITLE
No longer works with version 46.0.1

### ISSUE THREAD

**Issue by CCCM89** [dgutov/bmreplace#36]
as the title says, this add-on is no longer compatible.  will this be updated so that it works again?

**Comment by dgutov** [comment]
The version 1.5.11 should still work in Firefox 46.

**Comment by CCCM89** [comment]
that you for the prompt reply.  And at two in the morning, no less!  
This is why I love this add-on.  it works great, and the support is 
actually responsive.

**Comment by dgutov** [comment]
It's 12:34 over here. ;)
