### ISSUE TITLE
Problems with nightly 170726

### ISSUE THREAD

**Issue by SLK350** [dgutov/bmreplace#41]
Had to uninstall extension today to get firefox just working again. With extension installed I can't see any bookmarks and pinned tabs doesn't load.
This is with the latest nightly 64bit version.

**Comment by dgutov** [comment]
Thanks for the report. I can reproduce this, but not sure how to debug it. The error console shows "PlacesUIUtils is not defined", but not sure how that came to be.

No relevant backtraces from this extension's code.

**Comment by dgutov** [comment]
Let's see if it fixes itself in a few days, maybe 😫

**Comment by dgutov** [comment]
## Update

Removing, restarting, then trying to install it again gives this backtrace:

```
1501592884322	addons.xpi	WARN	Exception running bootstrap method startup on bmreplace@dgutov.github.com:
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIXPCComponents_Utils.import]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: 
"JS frame :: resource://gre/modules/addons/XPIProvider.jsm ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/bootstrap.js ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/content/bookmarks.js :: <TOP_LEVEL> :: line 4"  data: no] Stack trace: resource://gre/modules/addons/XPIProvider.jsm ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/bootstrap.js ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/content/bookmarks.js:4 < include()@resource://gre/modules/addons/XPIProvider.jsm ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/bootstrap.js:12 < startup()@resource://gre/modules/addons/XPIProvider.jsm ->
 jar:file:///home/dgutov/.mozilla/firefox/h1gy6udz.test/extensions/bmreplace@dgutov.github.com.xpi!/bootstrap.js:161 < callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4391 < startInstall/<()@resource://gre/modules/addons/XPIInstall.jsm:1935
```

**Comment by tomlevels** [comment]
Maybe you could file a bugreport on bugzilla?

**Comment by dgutov** [comment]
Yeah, I should try localizing the problem in a small extension and then file the report if it still makes sense. They might dismiss it, though, seeing as the next version of FF won't support this kind of addons anyway.

I've solved the above problem using lazy getters, but the next one came up: the `loadFrameScript` call, like, doesn't do anything anymore (when passed a chrome URL; `data:,` is okay).

**Comment by dgutov** [comment]
The nightly just got renumbered as Firefox 57. Could it be that the changes that broke this addon are only intended for 57 and newer?

We should check the beta as soon as it's 56.

**Comment by Manuela-Fereira** [comment]
Issue still present in 56 beta 1.

**Comment by dgutov** [comment]
@Manuela-Fereira Thanks for checking. I've posted a question on the forums: https://discourse.mozilla.org/t/legacy-addon-loadframescript-broken-in-firefox-56/17970

**Comment by dgutov** [comment]
In the meantime, everybody is welcome to try out https://github.com/dgutov/bmreplace/releases/tag/1.6.4b1

**Comment by SLK350** [comment]
Working fine! :) Thanks

**Comment by tomlevels** [comment]
After allowing legacy extensions, this version works fine with the latest nightlies, thanks!

**Comment by dgutov** [comment]
Thanks all for testing, submitted 1.6.4 for review.

**Comment by dgutov** [comment]
> this version works fine with the latest nightlies

Happy to hear that, but it'll probably break during the Firefox 57 development cycle, or whenever they really get rid of XUL, because we depend on `chrome://global/content/selectDialog.xul`.

**Comment by tomlevels** [comment]
I realise that, but still I can enjoy the extensions until that time :)
Do you have any progress on the webextension version of this extension?
